### PR TITLE
Feature: more icons

### PR DESCRIPTION
**Pull request by daniel-wtd**
- fixes: #11

### CODE REVIEW

**Comment by daniel-wtd** [comment]
@bilelmoussaoui Would be awesome, if you can have a look again.

PS: the build on pr is not triggered anymore?

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
The build is taking a bit of time to get started, you can track the queue  here https://flathub.org/builds/#/pendingbuildrequests

**Comment by daniel-wtd** [comment]
no problem ;) I will have a look later and tweak it, if needed.

**Comment by daniel-wtd** [comment]
Thank you a ot @bilelmoussaoui  :)

**Pull request merged**
