### PR TITLE
Update to Version 0.9.2b

### PR DESCRIPTION
**Pull request by second2050**

### CODE REVIEW

**Comment by daniel-wtd** [comment]
Hi, thanks for opening the PR. Please also update the com.shatteredpixel.shatteredpixeldungeon.appdata.xml with release information.

**Review by daniel-wtd — CHANGES_REQUESTED** [review]
Hi, thanks for opening the PR. Please also update the com.shatteredpixel.shatteredpixeldungeon.appdata.xml with release information.

**Comment by second2050** [comment]
> Hi, thanks for opening the PR. Please also update the com.shatteredpixel.shatteredpixeldungeon.appdata.xml with release information.

I have one problem with this now, the latest update on the flatpak `0.9.2-1` is dated as `2021-02-27` while the `0.9.2b` update is dated on their github as `2021-02-26`. How should this be correctly resolved? I just used `2021-02-26` as the date now.

**Comment by daniel-wtd** [comment]
The build issues seems not related to the date, but the version globbing/validation. Since 0.9.2-1 was not an upstream version, I would suggest removing the entire 0.9.2-1 block and re-build.

**Comment by second2050** [comment]
Okay I removed the `0.9.2-1` block from the `appdata.xml` and it builds now.

**Review by daniel-wtd — APPROVED** [review]

**Comment by daniel-wtd** [comment]
Thanks a lot. tested and merged.

**Pull request merged**
